### ISSUE TITLE
Are you sincere?

### ISSUE THREAD

**Issue by morizin** [jfhealthcare/Chexpert#32]
```
 ori_image: (H, W) numpy array of gray image
 logit_map: (H, W) numpy array of model prediction
 prob_map: (H, W) numpy array of model prediction with prob
```
is the size of the Logit maps is (H,W). when i train other network and removed the global pool layer and final linear layer then also i get the size of (N, C , 20,20) why is this like this when i print the shape of self.model.features or is this true

**Comment by yww211** [comment]
> ```
>  ori_image: (H, W) numpy array of gray image
>  logit_map: (H, W) numpy array of model prediction
>  prob_map: (H, W) numpy array of model prediction with prob
> ```
> 
> is the size of the Logit maps is (H,W). when i train other network and removed the global pool layer and final linear layer then also i get the size of (N, C , 20,20) why is this like this when i print the shape of self.model.features or is this true

Hi, 
Thanks for your interest in our project.
From your comment, i guess your question is what the shape of the logit_map is.
To your questions ,the shape of logit maps is (H, W), but H & W here are not the same as the (H, W) of the ori_image. The actual size of logit maps is downsampled by several times from the original image size. So that's why you got  (N, C , 20,20) output tensor size at the last Conv layer.
@morizin

**Comment by morizin** [comment]
Thanks for your reply. but while we are plotting heatmap 
if in my case: for each disease
original_image (512,512)
logit_map (20,20)
prob_map (20,20) 
will plot the heatmap

**Comment by yww211** [comment]
> Thanks for your reply. but while we are plotting heatmap
> if in my case: for each disease
> original_image (512,512)
> logit_map (20,20)
> prob_map (20,20)
> will plot the heatmap

sorry, i can't understand what you said. Can you update more detials in your question ? @morizin
